version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    target-branch: test-dependabot
  - package-ecosystem: npm
    directory: "/"
    schedule:
    target-branch: test-dependabot
