name: Deploy to GitHub Pages

on:
  push:
    branches:
      - test-workflow
  pull_request:
    branches:
      - test-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install dependencies
        run: npm install

      - name: Beautify HTML and CSS # use it on dev branch only
        run: npm run format

      - name: Verify CSS and correct
        run: npx stylelint --fix ./static/main.css

      #    - name: Verify HTML
      #      run: java -jar node_modules/vnu-jar/build/dist/vnu.jar --errors index.html

      - name: Minify HTML
        run: npx html-minifier-terser --input-dir ./static/ --output-dir ./static/ --file-ext html --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true --remove-style-link-type-attributes --trim-custom-fragments --no-include-auto-generated-tags
      
      - name: Minify CSS
        run: npx html-minifier-terser --input-dir ./static/ --output-dir ./static/ --file-ext css --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --remove-style-link-type-attributes --trim-custom-fragments --no-include-auto-generated-tags

      - name: Minify SVG
        run: npx svgo -f ./static/assets/svg/ -o ./static/assets/svg/

      - name: Push Changes # in test but that work
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'test-workflow'
