name: Code Quality checks
on:
  push:
    branches: [develop]
jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install -D
      - name: Check formatting with Prettier
        run: npm run prettier:format
