name: Code Quality (Stylelint)
on:
  push:
    branches: [develop]
jobs:
  prettier:
    name: Stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install -D
      - name: Check formatting with Stylelint
        run: npm run stylelint:check
        
